### ISSUE TITLE
Chr groups show - content mapping - link broken

### ISSUE THREAD

**Issue by sandrajhall** [mx3/mx#86]
http://mx-dev.nescent.org:3003/projects/1/chr_groups/2/show_content_mapping

**Comment by mjy** [comment]
Can't replicate.  Added some error catching logic/messages and cleaned up working view with html_safe.  Wil need a full strack trace if this commit doesn't work.

**Comment by sandrajhall** [comment]
Started GET "/projects/1/chr_groups/2/show_content_mapping" for 152.3.59.217 at 2012-06-12 13:40:34 -0400
  Processing by ChrGroupsController#show_content_mapping as HTML
  Parameters: {"proj_id"=>"1", "id"=>"2"}
Completed 500 Internal Server Error in 193ms

LoadError (no such file to load -- Strings):
  activesupport (3.0.12) lib/active_support/dependencies.rb:242:in `require'
  activesupport (3.0.12) lib/active_support/dependencies.rb:242:in`block in require'
  activesupport (3.0.12) lib/active_support/dependencies.rb:227:in `load_dependency'
  activesupport (3.0.12) lib/active_support/dependencies.rb:242:in`require'
  lib/linker.rb:6:in `<class:Linker>'
  lib/linker.rb:2:in`<top (required)>'
  activesupport (3.0.12) lib/active_support/dependencies.rb:242:in `require'
  activesupport (3.0.12) lib/active_support/dependencies.rb:242:in`block in require'
  activesupport (3.0.12) lib/active_support/dependencies.rb:227:in `load_dependency'
  activesupport (3.0.12) lib/active_support/dependencies.rb:242:in`require'
  activesupport (3.0.12) lib/active_support/dependencies.rb:350:in `require_or_load'
  activesupport (3.0.12) lib/active_support/dependencies.rb:491:in`load_missing_constant'
  activesupport (3.0.12) lib/active_support/dependencies.rb:183:in `block in const_missing'
  activesupport (3.0.12) lib/active_support/dependencies.rb:181:in`each'
  activesupport (3.0.12) lib/active_support/dependencies.rb:181:in `const_missing'
  activesupport (3.0.12) lib/active_support/dependencies.rb:503:in`load_missing_constant'
  activesupport (3.0.12) lib/active_support/dependencies.rb:183:in `block in const_missing'
  activesupport (3.0.12) lib/active_support/dependencies.rb:181:in`each'
  activesupport (3.0.12) lib/active_support/dependencies.rb:181:in `const_missing'
  app/controllers/chr_groups_controller.rb:29:in`show_content_mapping'
  actionpack (3.0.12) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.0.12) lib/abstract_controller/base.rb:150:in`process_action'
  actionpack (3.0.12) lib/action_controller/metal/rendering.rb:11:in `process_action'
  actionpack (3.0.12) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
  activesupport (3.0.12) lib/active_support/callbacks.rb:442:in `block in _run__2996569067516286404__process_action__2853004867890937916__callbacks'
  activesupport (3.0.12) lib/active_support/callbacks.rb:221:in`block in _conditional_callback_around_7372'
  app/controllers/application_controller.rb:71:in `ffx_xhr_redirect_hack'
  activesupport (3.0.12) lib/active_support/callbacks.rb:220:in`_conditional_callback_around_7372'
  activesupport (3.0.12) lib/active_support/callbacks.rb:441:in `_run__2996569067516286404__process_action__2853004867890937916__callbacks'
  activesupport (3.0.12) lib/active_support/callbacks.rb:410:in`_run_process_action_callbacks'
  activesupport (3.0.12) lib/active_support/callbacks.rb:94:in `run_callbacks'
  actionpack (3.0.12) lib/abstract_controller/callbacks.rb:17:in`process_action'
  actionpack (3.0.12) lib/action_controller/metal/rescue.rb:17:in `process_action'
  actionpack (3.0.12) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
  activesupport (3.0.12) lib/active_support/notifications.rb:52:in `block in instrument'
  activesupport (3.0.12) lib/active_support/notifications/instrumenter.rb:21:in`instrument'
  activesupport (3.0.12) lib/active_support/notifications.rb:52:in `instrument'
  actionpack (3.0.12) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  actionpack (3.0.12) lib/abstract_controller/base.rb:119:in `process'
  actionpack (3.0.12) lib/abstract_controller/rendering.rb:41:in`process'
  actionpack (3.0.12) lib/action_controller/metal.rb:138:in `dispatch'
  actionpack (3.0.12) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.0.12) lib/action_controller/metal.rb:178:in `block in action'
  actionpack (3.0.12) lib/action_dispatch/routing/route_set.rb:62:in`call'
  actionpack (3.0.12) lib/action_dispatch/routing/route_set.rb:62:in `dispatch'
  actionpack (3.0.12) lib/action_dispatch/routing/route_set.rb:27:in`call'
  rack-mount (0.6.14) lib/rack/mount/route_set.rb:148:in `block in call'
  rack-mount (0.6.14) lib/rack/mount/code_generation.rb:93:in`block in recognize'
  rack-mount (0.6.14) lib/rack/mount/code_generation.rb:551:in `optimized_each'
  rack-mount (0.6.14) lib/rack/mount/code_generation.rb:92:in`recognize'
  rack-mount (0.6.14) lib/rack/mount/route_set.rb:139:in `call'
  actionpack (3.0.12) lib/action_dispatch/routing/route_set.rb:493:in`call'
  sass (3.1.1) lib/sass/plugin/rack.rb:54:in `call'
  actionpack (3.0.12) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  actionpack (3.0.12) lib/action_dispatch/middleware/head.rb:14:in `call'
  rack (1.2.5) lib/rack/methodoverride.rb:24:in`call'
  actionpack (3.0.12) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.0.12) lib/action_dispatch/middleware/flash.rb:182:in`call'
  actionpack (3.0.12) lib/action_dispatch/middleware/session/abstract_store.rb:149:in `call'
  actionpack (3.0.12) lib/action_dispatch/middleware/cookies.rb:302:in`call'
  activerecord (3.0.12) lib/active_record/query_cache.rb:32:in `block in call'
  activerecord (3.0.12) lib/active_record/connection_adapters/abstract/query_cache.rb:28:in`cache'
  activerecord (3.0.12) lib/active_record/query_cache.rb:12:in `cache'
  activerecord (3.0.12) lib/active_record/query_cache.rb:31:in`call'
  activerecord (3.0.12) lib/active_record/connection_adapters/abstract/connection_pool.rb:354:in `call'
  actionpack (3.0.12) lib/action_dispatch/middleware/callbacks.rb:46:in`block in call'
  activesupport (3.0.12) lib/active_support/callbacks.rb:416:in `_run_call_callbacks'
  actionpack (3.0.12) lib/action_dispatch/middleware/callbacks.rb:44:in`call'
  rack (1.2.5) lib/rack/sendfile.rb:106:in `call'
  actionpack (3.0.12) lib/action_dispatch/middleware/remote_ip.rb:48:in`call'
  actionpack (3.0.12) lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
  railties (3.0.12) lib/rails/rack/logger.rb:13:in`call'
  rack (1.2.5) lib/rack/runtime.rb:17:in `call'
  rack (1.2.5) lib/rack/lock.rb:13:in`block in call'
  internal:prelude:10:in `synchronize'
  rack (1.2.5) lib/rack/lock.rb:13:in`call'
  railties (3.0.12) lib/rails/application.rb:168:in `call'
  railties (3.0.12) lib/rails/application.rb:77:in`method_missing'
  passenger (3.0.12) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  passenger (3.0.12) lib/phusion_passenger/abstract_request_handler.rb:513:in`accept_and_process_next_request'
  passenger (3.0.12) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  passenger (3.0.12) lib/phusion_passenger/rack/application_spawner.rb:206:in`start_request_handler'
  passenger (3.0.12) lib/phusion_passenger/rack/application_spawner.rb:171:in `block in handle_spawn_application'
  passenger (3.0.12) lib/phusion_passenger/utils.rb:479:in`safe_fork'
  passenger (3.0.12) lib/phusion_passenger/rack/application_spawner.rb:166:in `handle_spawn_application'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:357:in`server_main_loop'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:180:in`start'
  passenger (3.0.12) lib/phusion_passenger/rack/application_spawner.rb:129:in `start'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:253:in`block (2 levels) in spawn_rack_application'
  passenger (3.0.12) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:246:in`block in spawn_rack_application'
  passenger (3.0.12) lib/phusion_passenger/abstract_server_collection.rb:82:in `block in synchronize'
  <internal:prelude>:10:in`synchronize'
  passenger (3.0.12) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:244:in`spawn_rack_application'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:137:in `spawn_application'
  passenger (3.0.12) lib/phusion_passenger/spawn_manager.rb:275:in`handle_spawn_application'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.12) lib/phusion_passenger/abstract_server.rb:206:in`start_synchronously'
  passenger (3.0.12) helper-scripts/passenger-spawn-server:99:in `<main>'

**Comment by mjy** [comment]
Aha.  We have to use fully qualified(?) references to module names.
The Strings module will need to be sunk into a "Toolbox" module and
referenced in that way ... ToolBox::Strings.   See Figurable for an
example. (but we can use module Toolbox::Strings I think...).

M

On Tue, Jun 12, 2012 at 12:47 PM, Sandra Hall
reply@reply.github.com
wrote:
